# SPDX-License-Identifier: GPL-2.0
#
# Kbuild for top-level directory of the kernel

# Prepare global headers and check sanity before descending into sub-directories
# ---------------------------------------------------------------------------

obj-y			+= drivers/

# Backport from 6.14 to 6.10 to 6.13
INCLUDES += \
	-include $(PWD)/include/uapi/linux/ntsync.h \
	-I$(PWD)/include/

ccflags-y += $(INCLUDES)
subdir-ccflags-y += $(INCLUDES)

#ccflags-y += -H
